name: Hello World

on:
  push:   # runs whenever you push to any branch
    branches:
      - dev

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Say Hello
        run: echo "Hello World from GitHub Actions 🚀"

